site_name: Josh's Projects & Blog
site_url: https://odyhibit.github.io/    # adjust later
theme:
  name: material
  # You can add extra Material tweaks here (palette, font, icons, etc.)
nav:
  - Home: index.md
  - Projects:
      - ASCII→Bitmap: posts/ascii-to-bitmap/index.md
      - Any-bits-you-want-stego: posts/any-bits-you-want-stego/index.md
